packages:
  - .

overrides:
  undici: 5.28.3

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
  - unrs-resolver

allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
